---
- set_fact:
    fs_name: "{{ group_names[0] }}"
    mgs_disk_interface: "{{ beegfs_host_info[mgs_host][disks[0]]['if'] }}"
  tags: [ 'never', 'create_storage', 'stop']

- set_fact:
    mgs_ip: "{{ beegfs_host_info[mgs_host][mgs_disk_interface] }}"
    storage_interfaces: "{{ disks|map('extract', beegfs_host_info[ansible_host])|map(attribute='if')|unique|list }}"
  tags: [ 'never', 'create_storage']

- debug:
    msg: "{{ storage_interfaces }}"
  tags: [ 'never', 'create_storage']


- name: create storage config dirs
  file:
    path: "/etc/beegfs/{{ fs_name }}/{{ item }}.d/"
    state: directory
  loop: "{{ disks }}"
  tags: [ 'never', 'create_storage']

- name: add template storage conf
  command: "cp /etc/beegfs/beegfs-storage.conf /etc/beegfs/{{ fs_name }}/{{ item }}.d/beegfs-storage.conf"
  args:
    creates: "/etc/beegfs/{{ fs_name }}/{{ item }}.d/beegfs-storage.conf"
  loop: "{{ disks }}"
  tags: [ 'never', 'create_storage']

- name: make data dir
  file:
    path: "/data/{{ fs_name }}/{{ item }}/data"
    state: directory
    recurse: yes
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'create_storage']

- name: setup target
  command: |
      /opt/beegfs/sbin/beegfs-setup-storage \
      -p /data/{{ fs_name }}/{{ item }}/data \
      -i {{ beegfs_host_info[ansible_host][item]['storage_index'] }} \
      -s {{ beegfs_host_info[ansible_host][item]['storage_index'] }} \
      -m {{ mgs_ip }}
      -c /etc/beegfs/{{ fs_name }}/{{ item }}.d/beegfs-storage.conf
      -I {{ item }}
      -S {{ ansible_host }}-{{ item }}
  register: command_result
  failed_when: "command_result.rc != 0 and ('ERROR: Storage target directory is not empty.' not in command_result.stdout)"
  changed_when: "command_result.rc == 0"
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'create_storage']

- name: set TCP storage port
  lineinfile:
    path: "/etc/beegfs/{{ fs_name }}/{{ item }}.d/beegfs-storage.conf"
    regexp: '^connStoragePortTCP.*'
    line: "connStoragePortTCP = {{ beegfs_host_info[ansible_host][item]['str_port'] }}"
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'create_storage']

- name: set UDP storage port
  lineinfile:
    path: "/etc/beegfs/{{ fs_name }}/{{ item }}.d/beegfs-storage.conf"
    regexp: '^connStoragePortUDP.*'
    line: "connStoragePortUDP = {{ beegfs_host_info[ansible_host][item]['str_port'] }}"
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'create_storage']

- name: set storage log
  lineinfile:
    path: "/etc/beegfs/{{ fs_name }}/{{ item }}.d/beegfs-storage.conf"
    regexp: '^logStdFile.*'
    line: "logStdFile = /var/log/beegfs-storage-{{ fs_name }}-{{ item }}.log"
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'create_storage']

- name: Start Services storage
  systemd:
    state: started
    name: "beegfs-storage@{{ fs_name }}-{{ item }}.service"
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'create_storage']

- name: Stop Services storage
  systemd:
    state: stopped
    name: "beegfs-storage@{{ fs_name }}-{{ item }}.service"
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'stop']
