---
- set_fact:
    fs_name: "{{ group_names[0] }}"
    mgs_disk_interface: "{{ beegfs_host_info[mgs_host][disks[0]]['if'] }}"
  tags: [ 'never', 'create_mgs_mds', 'stop']

- set_fact:
    fs_config_dir: "/etc/beegfs/{{ fs_name }}.d/"
    mgs_dir: "/data/{{ fs_name }}/{{ disks[0] }}/mgs"
    mds_dir: "/data/{{ fs_name }}/{{ disks[0] }}/mds"
    mgs_ip: "{{ beegfs_host_info[mgs_host][mgs_disk_interface] }}"
    mgs_port: "{{ beegfs_host_info[mgs_host][disks[0]]['mgs_port'] }}"
    mds_port: "{{ beegfs_host_info[mgs_host][disks[0]]['mds_port'] }}"
  tags: [ 'never', 'create_mgs_mds']

- name: create fs config dir
  file:
    path: "{{ fs_config_dir }}"
    state: directory
  tags: [ 'never', 'create_mgs_mds']

- name: Copy default config
  shell: "cp /etc/beegfs/*.conf {{ fs_config_dir }}"
  args:
    creates: "{{ fs_config_dir }}beegfs-admon.conf"
  tags: [ 'never', 'create_mgs_mds']


- name: BeeGFS mgmtd
  command: "/opt/beegfs/sbin/beegfs-setup-mgmtd -p {{ mgs_dir }} -n -S {{ fs_name }} -c {{fs_config_dir}}beegfs-mgmtd.conf"
  register: command_result
  failed_when: "command_result.rc != 0 and ('ERROR: Storage directory is not empty.' not in command_result.stdout)"
  changed_when: "command_result.rc == 0"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'create_mgs_mds']

- name: set mgmtd port
  lineinfile:
    path: "{{ fs_config_dir }}beegfs-mgmtd.conf"
    regexp: '^{{ item }}.*'
    line: "{{ item }} = {{ mgs_port }}"
  loop:
    - "connMgmtdPortTCP"
    - "connMgmtdPortUDP"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'create_mgs_mds']
# TODO: log file also?

- name: Start mgmtd
  systemd:
    state: started
    name: "beegfs-mgmtd@{{ fs_name }}.service"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'create_mgs_mds']

- name: Stop mgmtd
  systemd:
    state: stopped
    name: "beegfs-mgmtd@{{ fs_name }}.service"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'stop']


- name: Configure BeeGFS primary mds
  command: "/opt/beegfs/sbin/beegfs-setup-meta -p {{ mds_dir }} -s {{ '%s'|format(beegfs_host_info[mgs_host][disks[0]]['storage_index']) }} -m {{ mgs_ip }} -S {{ fs_name }} -c {{fs_config_dir}}beegfs-meta.conf"
  register: command_result
  failed_when: "command_result.rc != 0 and ('ERROR: Storage directory is not empty.' not in command_result.stdout)"
  changed_when: "command_result.rc == 0"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'create_mgs_mds']

- name: set meta port
  lineinfile:
    path: "{{ fs_config_dir }}beegfs-meta.conf"
    regexp: '^{{ item }}.*'
    line: "{{ item }} = {{ mds_port }}"
  loop:
    - "connMetaPortTCP"
    - "connMetaPortUDP"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'create_mgs_mds']

- name: set mgmtd port for meta
  lineinfile:
    path: "{{ fs_config_dir }}beegfs-meta.conf"
    regexp: '^{{ item }}.*'
    line: "{{ item }} = {{ mgs_port }}"
  loop:
    - "connMgmtdPortTCP"
    - "connMgmtdPortUDP"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'create_mgs_mds']
# TODO: update log file in config file...?

- name: Start meta
  systemd:
    state: started
    name: "beegfs-meta@{{ fs_name }}.service"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'create_mgs_mds']

- name: stop meta
  systemd:
    state: stopped
    name: "beegfs-meta@{{ fs_name }}.service"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'stop']
