---
- set_fact:
    fs_name: "{{ group_names[0] }}"
    mgs_disk_interface: "{{ beegfs_host_info[mgs_host][disks[0]]['if'] }}"
  tags: [ 'never', 'create_storage']

- set_fact:
    mgs_ip: "{{ beegfs_host_info[mgs_host][mgs_disk_interface] }}"
    storage_interfaces: "{{ disks|map('extract', beegfs_host_info[ansible_host])|map(attribute='if')|unique|list }}"
  tags: [ 'never', 'create_storage']

- debug:
    msg: "{{ storage_interfaces }}"
  tags: [ 'never', 'create_storage']


- name: create storage config dirs
  file:
    path: "/etc/beegfs/{{ fs_name }}-{{ item }}.d/"
    state: directory
  loop: "{{ disks }}"
  tags: [ 'never', 'create_storage']

- name: add template storage conf
  command: "cp /etc/beegfs/beegfs-storage.conf /etc/beegfs/{{ fs_name }}-{{ item }}.d/beegfs-storage.conf"
  args:
    creates: "/etc/beegfs/{{ fs_name }}-{{ item }}.d/beegfs-storage.conf"
  loop: "{{ disks }}"
  tags: [ 'never', 'create_storage']

- name: make data dir
  file:
    path: "/data/{{ fs_name }}/{{ item }}/data"
    state: directory
    recurse: yes
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'create_storage']

- name: setup target
  command: |
      /opt/beegfs/sbin/beegfs-setup-storage \
      -p /data/{{ fs_name }}/{{ item }}/data \
      -i {{ beegfs_host_info[ansible_host][item]['storage_index'] }} \
      -s {{ beegfs_host_info[ansible_host][item]['storage_index'] }} \
      -m {{ mgs_ip }}
      -c /etc/beegfs/{{ fs_name }}-{{ item }}.d/beegfs-storage.conf
      -I {{ item }}
      -S {{ ansible_host }}-{{ item }}
  register: command_result
  failed_when: "command_result.rc != 0 and ('ERROR: Storage directory is not empty.' not in command_result.stdout)"
  changed_when: "command_result.rc == 0"
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'create_storage']

- name: set TCP storage port
  lineinfile:
    path: "/etc/beegfs/{{ fs_name }}-{{ item }}.d/beegfs-storage.conf"
    regexp: '^connStoragePortTCP.*'
    line: "connStoragePortTCP = {{ beegfs_host_info[ansible_host][item]['str_port'] }}"
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'create_storage']

- name: set UDP storage port
  lineinfile:
    path: "/etc/beegfs/{{ fs_name }}-{{ item }}.d/beegfs-storage.conf"
    regexp: '^connStoragePortUDP.*'
    line: "connStoragePortUDP = {{ beegfs_host_info[ansible_host][item]['str_port'] }}"
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'create_storage']

- name: Start Services storage
  systemd:
    state: started
    name: "beegfs-storage@{{ fs_name }}-{{ item }}.service"
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'create_storage']

#TODO... rest of config!!


- name: get node ides
  debug:
    msg: "{{ index%2+1  }}"
  loop: "{{ osts|flatten }}"
  loop_control:
    index_var: index
  register: index_mod
  tags: [ 'never', 'create_osts']

- set_fact:
    node_id: "{{ index_mod.results | map(attribute='msg') | list}}"
  tags: [ 'never', 'create_osts']


- name: setup target
  command: /opt/beegfs/sbin/beegfs-setup-storage -f -p /data/oss/{{item.0}} -s {{item.1}} -S {{inventory_hostname}}-{{item.1}}
  loop : "{{ (osts|flatten)|zip((node_id|sort()))|list }}"
  when:
    - osts is defined
  tags: [ 'never', 'create_osts']


- name: set targets BeeGFS storage conf
  lineinfile:
    path: /etc/beegfs/{{ group_names[0]}}/{{index}}.d/beegfs-storage.conf
    regexp: '^storeStorageDirectory'
    line: "storeStorageDirectory=,/data/oss/{{ ' ,/data/oss/'.join(item) }}"
  loop: "{{ osts }}"
  loop_control:
    index_var: index
  when:
    - osts is defined
  tags: [ 'never', 'create_osts']

- name: set beegfs storage port
  lineinfile:
    path: /etc/beegfs/{{ group_names[0]}}/{{index}}.d/beegfs-storage.conf
    regexp: '^connStoragePortTCP'
    line: "connStoragePortTCP={{'80%s3'|format(index)}}"
  loop: "{{ osts }}"
  loop_control:
    index_var: index
  when:
    - osts is defined
  tags: [ 'never', 'create_osts']

- name: set beegfs storage port
  lineinfile:
    path: /etc/beegfs/{{ group_names[0]}}/{{index}}.d/beegfs-storage.conf
    regexp: '^connStoragePortUDP'
    line: "connStoragePortUDP={{'80%s3'|format(index)}}"
  loop: "{{ osts }}"
  loop_control:
    index_var: index
  when:
    - osts is defined
  tags: [ 'never', 'create_osts']


- name: init on start BeeGFS storage conf
  lineinfile:
    path: /etc/beegfs/{{ group_names[0]}}/{{index}}.d/beegfs-storage.conf
    regexp: '^storeAllowFirstRunInit'
    line: "storeAllowFirstRunInit=true"
  loop: "{{ osts }}"
  loop_control:
    index_var: index
  tags: [ 'never', 'create_osts']

- name: init on start BeeGFS storage conf
  lineinfile:
    path: /etc/beegfs/{{ group_names[0]}}/{{index}}.d/beegfs-storage.conf
    regexp: '^tuneNumWorkers'
    line: "tuneNumWorkers=12"
  loop: "{{ osts }}"
  loop_control:
    index_var: index
  tags: [ 'never', 'create_osts']

- name: set log location
  lineinfile:
    path: /etc/beegfs/{{ group_names[0]}}/{{index}}.d/beegfs-storage.conf
    regexp: '^logStdFile'
    line: "logStdFile=/var/log/beegfs-storage-{{group_names[0]}}-{{index}}.log"
  loop: "{{ osts }}"
  loop_control:
    index_var: index
  tags: [ 'never', 'create_osts']

- name: Start Services storage
  systemd:
    state: started
    name: "beegfs-storage@{{group_names[0]}}-{{index}}.service"
  loop: "{{ osts }}"
  loop_control:
    index_var: index
  when:
    - osts is defined
  tags: [ 'never', 'start_service']
