---
- set_fact:
    fs_name: "{{ group_names[0] }}"
    mgs_disk_interface: "{{ beegfs_host_info[mgs_host][disks[0]]['if'] }}"
  tags: [ 'never', 'create_mgs_mds']

- set_fact:
    fs_config_dir: "/etc/beegfs/{{ fs_name }}.d/"
    mgs_dir: "/data/{{ fs_name }}/{{ disks[0] }}/mgs"
    mds_dir: "/data/{{ fs_name }}/{{ disks[0] }}/mds"
    mgs_ip: "{{ beegfs_host_info[mgs_host][mgs_disk_interface] }}"
  tags: [ 'never', 'create_mgs_mds']


- name: create fs config dir
  file:
    path: "{{ fs_config_dir }}"
    state: directory
  tags: [ 'never', 'create_mgs_mds']

- name: Copy default config
  shell: "cp /etc/beegfs/*.conf {{ fs_config_dir }}"
  args:
    creates: "{{ fs_config_dir }}beegfs-admon.conf"
  tags: [ 'never', 'create_mgs_mds']


- name: BeeGFS mgmtd
  command: "/opt/beegfs/sbin/beegfs-setup-mgmtd -p {{ mgs_dir }} -n -S {{ fs_name }} -c {{fs_config_dir}}beegfs-mgmtd.conf"
  register: command_result
  failed_when: "command_result.rc != 0 and ('ERROR: Storage directory is not empty.' not in command_result.stdout)"
  changed_when: "command_result.rc == 0"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'create_mgs_mds']

# TODO: update port in config file...?

- name: Start mgmtd
  systemd:
    state: started
    name: "beegfs-mgmtd@{{ fs_name }}.service"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'create_mgs_mds']


- name: Configure BeeGFS primary mds
  command: "/opt/beegfs/sbin/beegfs-setup-meta -p {{ mgs_dir }} -s 1 -m {{ mgs_ip }} -S {{ fs_name }} -c {{fs_config_dir}}beegfs-meta.conf"
  register: command_result
  failed_when: "command_result.rc != 0 and ('ERROR: Storage directory is not empty.' not in command_result.stdout)"
  changed_when: "command_result.rc == 0"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'create_mgs_mds']

# TODO: update port in config file...?

- name: Start meta
  systemd:
    state: started
    name: "beegfs-meta@{{ fs_name }}.service"
  when:
    - mgs_host == ansible_host
  tags: [ 'never', 'create_mgs_mds']


- name: BeeGFS mgmtd conf
  lineinfile:
    path: /etc/beegfs/beegfs-mgmtd.conf
    regexp: '^storeMgmtdDirectory'
    line: 'storeMgmtdDirectory=/data/mgmtd'
  when:
    - false
  tags: [ 'never', 'create_mgs']


- name: Add MDS address
  lineinfile:
    path: /etc/beegfs/beegfs-meta.conf
    regexp: '^sysMgmtdHost'
    line: "sysMgmtdHost={{ ansible_ib0.ipv4.address}}"
  when:
    - mds is defined
  tags: [ 'never', 'create_mds']

- name: Set MDS dir
  lineinfile:
    path: /etc/beegfs/beegfs-meta.conf
    regexp: '^storeMetaDirectory'
    line: "storeMetaDirectory=/data/mds/{{ item}}"
  loop: "{{ mds }}"
  when:
    - mds is defined
  tags: [ 'never', 'create_mds']

- name: Beegfs Format MDS
  lineinfile:
    path: /etc/beegfs/beegfs-meta.conf
    regexp: '^storeAllowFirstRunInit'
    line: "storeAllowFirstRunInit=true"
  when:
    - mds is defined
  tags: [ 'never', 'create_mds']

- name: Start services mgmtd
  systemd:
    state: started
    name: beegfs-mgmtd
  when:
    - mgs is defined
  tags: [ 'never', 'start_service']

