---
- name: Format disks
  command: mkfs.ext4 -i 16384 -I 512 -J size=400 -Odir_index,filetype /dev/{{item}}
  loop: "{{ disks }}"
  when:
    - disks is defined
  tags: [ 'never', 'format']

- name: Setup disks
  block:

    - name: Create mount point dir
      file:
        path: /data/{{ group_names[0] }}/{{ item }}
        state: directory
        recurse: yes
      loop: "{{ disks }}"

    - name: Mount EXT4 OSTs
      command: mount -onoatime,nodiratime,nobarrier,user_xattr /dev/{{item}} /data/{{ group_names[0] }}/{{ item }}
      register: command_result
      failed_when: "command_result.rc != 0 and ('is already mounted' not in command_result.stderr)"
      changed_when: "command_result.rc == 0"
      loop: "{{ disks }}"

  when:
    - disks is defined
  tags: [ 'never', 'mount']


- set_fact:
    fs_name: "{{ group_names[0] }}"

- block:
    - set_fact:
        mds_dir: "/data/{{ fs_name }}/{{ disks[0] }}/mds"
    - name: make metadata dir
      file:
        path: "{{ mds_dir }}"
        state: directory
        recurse: yes
      tags: [ 'never', 'mount']
  when:
    - disks is defined
    - mds_host == ansible_host


- block:
    - set_fact:
        mgs_dir: "/data/{{ fs_name }}/{{ disks[0] }}/mgs"
    - name: make management dir
      file:
        path: "{{ mgs_dir }}"
        state: directory
        recurse: yes
      tags: [ 'never', 'mount']
  when:
    - disks is defined
    - mgs_host == ansible_host

- name: Unmount disks
  block:

    - name: Mount EXT4 OSTs
      command: umount -l /data/{{ group_names[0] }}/{{ item }}
      register: command_result
      failed_when: "command_result.rc != 0 and ('not mounted' not in command_result.stderr) and ('mountpoint not found' not in command_result.stderr)"
      changed_when: "command_result.rc == 0"
      loop: "{{ disks }}"

    - name: Remove mount point dir
      file:
        path: /data/{{ group_names[0] }}
        state: absent

  when:
    - disks is defined
  tags: [ 'never', 'unmount']
