---

- name: flush arp ib
  command: ip neigh flush dev {{ item }}
  with_items:
      - ib0
      - ib1

- name: update routes2
  blockinfile:
    path: /etc/iproute2/rt_tables
    block: |
      200 ib0
      201 ib1

- name: static routes {{ item.name }}
  command: ip route add 10.47.0.0/16 dev {{ item.name }} proto kernel scope link src {{ item.addr }} table {{ item.name }}
  with_items: "{{ ip }}"
  when:
    - ip is defined
    - item.name is match(target|default(".*"))
  tags: [ 'never' , 'init_routes' ]

- name: ib static routes
  command: ip rule add from {{ item.addr }} table {{ item.name }}
  with_items: "{{ ip }}"
  when:
    - ip is defined
    - item.name is match(target|default(".*"))
  tags: [ 'never' , 'init_routes' ]

- name: ib route flush
  command: ip route flush cache
