---

- name: Format OSTs XFS
  command: mkfs.xfs -f /dev/{{item.name}}
  with_items: "{{ osts }}"
  when:
    - osts is defined
    - item.name is match(target|default(".*"))
  tags: [ 'never', 'create_osts']

- name: OSS mount point
  file: 
    path: /data/oss/{{item.name}}
    state: directory
    recurse: yes
  with_items: "{{ osts }}"
  when:
    - osts is defined
    - item.name is match(target|default(".*"))
  tags: [ 'never', 'create_osts']



- name: Mount XFS OSTs
  command: mount -onoatime,nodiratime,logbufs=8,logbsize=256k,largeio,inode64,swalloc,allocsize=131072k,nobarrier /dev/{{item.name}} /data/oss/{{item.name}}
  with_items: "{{ osts }}"
  when:
    - osts is defined
    - item.name is match(target|default(".*"))
  tags: [ 'never', 'create_osts']

- name: clean BeeGFS storage conf
  lineinfile:
    path: /etc/beegfs/beegfs-storage.conf
    regexp: '^storeStorageDirectory'
    line: "storeStorageDirectory = "
  tags: [ 'never', 'format_osts']



- name: Format BeeGFS OSTs
  command: /opt/beegfs/sbin/beegfs-setup-storage -f -p /data/oss/{{item.name}} -s {{ item.sid }} -i {{item.index}} -m {{inventory_hostname}}
  with_items: "{{ osts }}"
  when:
    - osts is defined
    - item.name is match(target|default(".*"))
  tags: [ 'never', 'format_osts']


