---

- name: connInterfacesFile
  blockinfile:
    create: yes
    path: /etc/beegfs/connInterfacesFile
    block: |
      ib0
  tags: [ 'never', 'create_mds']

- name: connNetFilterFile
  blockinfile:
    create: yes
    path: /etc/beegfs/connNetFilterFile
    block: |
      10.47.18.0/16
  tags: [ 'never', 'create_mds']

- name: set meta interfaces
  lineinfile:
    path: /etc/beegfs/beegfs-meta.conf
    regexp: '^connInterfacesFile'
    line: 'connInterfacesFile=/etc/beegfs/connInterfacesFile'
  tags: [ 'never', 'create_mds']


- name: set storage interfaces
  lineinfile:
    path: /etc/beegfs/beegfs-storage.conf
    regexp: '^connInterfacesFile'
    line: 'connInterfacesFile=/etc/beegfs/connInterfacesFile'
  tags: [ 'never', 'create_mds']

- name: set meta interfaces
  lineinfile:
    path: /etc/beegfs/beegfs-meta.conf
    regexp: '^connNetFilterFile'
    line: 'connNetFilterFile=/etc/beegfs/connNetFilterFile'
  tags: [ 'never', 'create_mds']

- name: set storage interfaces
  lineinfile:
    path: /etc/beegfs/beegfs-storage.conf
    regexp: '^connNetFilterFile'
    line: 'connNetFilterFile=/etc/beegfs/connNetFilterFile'
  tags: [ 'never', 'create_mds']

