---
- hosts: all
  become: true
  tasks:
  - name: configure default gateway
    command: route add default gw 10.43.255.1
    register: command_result
    failed_when: "command_result.rc != 0 and ('SIOCADDRT: File exists' not in command_result.stderr)"
    changed_when: "command_result.rc == 0"
  - name: Create entries in /etc/hosts for all nodes
    lineinfile:
      path: /etc/hosts
      line: "{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['ansible_hostname'] }} {{ item }}"
      regexp: "^.* {{ item }}$"
      create: no
      state: present
    with_items:
      - "{{ ansible_play_hosts }}"

- hosts: etcd-master[0]
  roles:
    - role: andrewrothstein.pki
      pki_dir: /home/centos/pki-dir
      pki_self_sign: True
      pki_ca:
        cname: ca.dac.hpc.cam.ac.uk
      pki_servers:
        - cname: dac-etcd.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac-etcd.dac.hpc.cam.ac.uk
          altips:
            - '10.43.101.30'
        - cname: dac1.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac1.dac.hpc.cam.ac.uk
        - cname: dac2.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac2.dac.hpc.cam.ac.uk
        - cname: dac3.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac3.dac.hpc.cam.ac.uk
        - cname: dac-slurm-master.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac-slurm-master.dac.hpc.cam.ac.uk
        - cname: slurm-cpu1.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - slurm-cpu1.dac.hpc.cam.ac.uk

- hosts: etcd-master[0]
  tasks:
    - fetch:
        src: /home/centos/pki-dir/{{item}}
        dest: ~/pki-dir/
        flat: yes
      with_items:
        - ca.pem
        - ca-key.pem
        - dac-etcd.dac.hpc.cam.ac.uk.pem
        - dac-etcd.dac.hpc.cam.ac.uk-key.pem
        - dac1.dac.hpc.cam.ac.uk.pem
        - dac1.dac.hpc.cam.ac.uk-key.pem
        - dac2.dac.hpc.cam.ac.uk.pem
        - dac2.dac.hpc.cam.ac.uk-key.pem
        - dac3.dac.hpc.cam.ac.uk.pem
        - dac3.dac.hpc.cam.ac.uk-key.pem
        - dac-slurm-master.dac.hpc.cam.ac.uk.pem
        - dac-slurm-master.dac.hpc.cam.ac.uk-key.pem
        - slurm-cpu1.dac.hpc.cam.ac.uk.pem
        - slurm-cpu1.dac.hpc.cam.ac.uk-key.pem

- hosts: etcd
  roles:
    - role: andrewrothstein.etcd-cluster

- hosts: dac-workers
  become: true
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip

- hosts: dac-workers
  become: True
  tasks:
    - name: ensure kernel dev tools available for beegfs client autobuild
      package:
        name: kernel-devel
    - name: ensure dev tools available for beegfs client autobuild
      package:
        name: gcc
    - selinux:
        state: disabled

- hosts: dac-workers
  roles:
    - role: data-acc

- hosts: dac-workers[0]
  become: true
  become_user: dac
  tasks:
    - name: Create ssh key for dac user for fs-ansible
      shell: |
        ssh-keygen -f /var/lib/dac/.ssh/id_rsa -t rsa -N ''
        cat /var/lib/dac/.ssh/id_rsa.pub >> /var/lib/dac/.ssh/authorized_keys
      args:
         creates: /var/lib/dac/.ssh/id_rsa
    - name: Pull Keys
      synchronize:
        mode: pull
        src:  /var/lib/dac/.ssh/
        dest: ~/.dac.ssh/
        recursive: yes

- hosts: dac-workers
  become: true
  tasks:
    - name: Push Keys for dac user for fs-ansible
      synchronize:
        mode: push
        src: ~/.dac.ssh/
        dest:  /var/lib/dac/.ssh/
        recursive: yes
    - name: trust host keys
      shell: |
        ssh-keyscan {{ hostvars[item]['ansible_host'] }} >> /var/lib/dac/.ssh/known_hosts
        ssh-keyscan {{ hostvars[item]['ansible_hostname'] }} >> /var/lib/dac/.ssh/known_hosts
        ssh-keyscan {{ item }} >> /var/lib/dac/.ssh/known_hosts
        touch /var/lib/dac/.ssh/.known{{ hostvars[item]['ansible_host'] }}
      args:
         creates: "/var/lib/dac/.ssh/.known{{ hostvars[item]['ansible_host'] }}"
      with_items: "{{ ansible_play_hosts }}"
    - name: Fix up permissions on .ssh
      file:
        path: /var/lib/dac/.ssh
        owner: dac
        group: dac
        recurse: yes
    - name: Ensure passwordless sudo for dac user
      lineinfile:
        path: /etc/sudoers.d/80-dac
        line: "dac ALL=(ALL) NOPASSWD:ALL"
        regexp: "^dac.*$"
        create: yes
        state: present

- hosts: slurm
  become: true
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
    docker_users:
      - "centos"
    docker_compose_version: "1.22.0"
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker

- hosts: slurm-master[0]
  become: true
  vars:
      recreate: false
  tasks:
    - file:
        path: /var/lib/slurm-docker
        state: directory
        mode: 0755
    - name: docker service description to host
      synchronize:
        mode: push
        src: "{{ playbook_dir }}/slurm-master"
        dest:  /var/lib/slurm-docker/
        recursive: yes
        links: no
        copy_links: yes
    - file:
        path: /etc/data-acc/pki
        state: directory
        mode: 0700
        owner: 995
        group: 995
    - name: copy etcd keys
      become: yes
      become_user: root
      copy:
        src: '{{item}}'
        dest: /etc/data-acc/pki
        owner: '995' # TODO...
        group: '995'
        mode: 0700
      with_items:
        - '~/pki-dir/{{inventory_hostname}}.pem'
        - '~/pki-dir/{{inventory_hostname}}-key.pem'
        - '~/pki-dir/ca.pem'
    - name: pull docker images
      # https://github.com/ansible/ansible/issues/47978
      command: docker-compose pull
      args:
        chdir: '/var/lib/slurm-docker/slurm-master'
      changed_when: False
    - docker_service:
        project_src: /var/lib/slurm-docker/slurm-master
        state: absent
        remove_volumes: yes
      when: recreate|bool
    - docker_service:
        project_src: /var/lib/slurm-docker/slurm-master
      register: output
    - name: ensure slurm cluster registered in db
      shell: |
        sleep 10 && docker exec slurmctld bash -c "/usr/bin/sacctmgr --immediate add cluster name=linux" && docker restart slurmdbd slurmctld
      register: shell_result
      changed_when: "shell_result.rc == 0"
      failed_when: "shell_result.rc != 0 and ('already exists' not in shell_result.stdout)"
      when: output.changed

- hosts: slurm-workers
  become: true
  vars:
      recreate: false
  tasks:
    - file:
        path: /var/lib/slurm-docker/
        state: directory
        mode: 0755
    - name: docker service description to host
      synchronize:
        mode: push
        src: "{{ playbook_dir }}/slurm-worker"
        dest:  /var/lib/slurm-docker/
        recursive: yes
        links: no
        copy_links: yes
    - file:
        path: /etc/data-acc/pki
        state: directory
        mode: 0700
        owner: root
        group: root
    - name: copy etcd keys
      become: yes
      become_user: root
      copy:
        src: '{{item}}'
        dest: /etc/data-acc/pki
        owner: 'root' # TODO...
        group: 'root'
        mode: 0700
      with_items:
        - '~/pki-dir/{{inventory_hostname}}.pem'
        - '~/pki-dir/{{inventory_hostname}}-key.pem'
        - '~/pki-dir/ca.pem'
    - name: pull docker images
      # https://github.com/ansible/ansible/issues/47978
      command: docker-compose pull
      args:
        chdir: '/var/lib/slurm-docker/slurm-worker'
      changed_when: False
    - docker_service:
        project_src: /var/lib/slurm-docker/slurm-worker
        state: absent
        remove_volumes: yes
      when: recreate|bool
    - docker_service:
        project_src: /var/lib/slurm-docker/slurm-worker
