---
- set_fact:
    mgs: "{{ vars[fs_name + '_mgs'] | default(omit) }}"
    mgsnode: "{{ vars[fs_name + '_mgsnode'] }}"
    mdts: "{{ vars[fs_name + '_mdts'] | default({}) }}"
    osts: "{{ vars[fs_name + '_osts'] | default({}) }}"
    client_port: "{{ vars[fs_name + '_client_port'] }}"
    mdt_size: "{{ vars[fs_name + '_mdt_size'] | default('20GiB') }}"
  tags: [ 'never', 'format_mgs', 'reformat_mgs', 'format']

- name: Ensure MGS has been formatted
  command: /usr/sbin/mkfs.lustre --mgs /dev/{{ mgs }}
  register: command_result
  failed_when: "command_result.rc != 0 and ('was previously formatted for lustre' not in command_result.stderr) and command_result.rc != 17"
  changed_when: "command_result.rc == 0"
  when:
    - mgs is defined
  tags: [ 'never', 'format_mgs', 'format']

- name: Reformat MGS
  command: /usr/sbin/mkfs.lustre --mgs --reformat /dev/{{ mgs }}
  when:
    - mgs is defined
  tags: [ 'never', 'reformat_mgs']

- name: Add MDT Partition
  parted:
     device: "/dev/{{ item }}"
     number: 1
     part_start: "0%"
     part_end: "{{ mdt_size }}"
     label: gpt
     state: present
  loop: "{{ mdts.keys() }}"
  when:
    - mdts is defined
  tags: [ 'never', 'reformat_mdts', 'format']

- name: Reformat MDTs
  command: "/usr/sbin/mkfs.lustre --mdt --reformat --fsname={{ fs_name }} --index={{ item.value }} --mgsnode={{ mgsnode }}{{ lnet_suffix }} /dev/{{ item.key }}1"
  loop: "{{ mdts|dict2items }}"
  when:
    - mdts is defined
  tags: [ 'never', 'reformat_mdts', 'format']

- name: Add OST Partition
  parted:
     device: "/dev/{{ item }}"
     number: 2
     part_start: "{{ mdt_size }}"
     part_end: "100%"
     label: gpt
     state: present
  loop: "{{ osts.keys() }}"
  when:
    - mdts is defined
  tags: [ 'never', 'reformat_mdts', 'format']

- name: Reformat OSTs
  command: "/usr/sbin/mkfs.lustre --ost --reformat --fsname={{ fs_name }} --index={{ item.value }} --mgsnode={{ mgsnode }}{{ lnet_suffix }} /dev/{{ item.key }}2"
  loop: "{{ osts|dict2items }}"
  when:
    - osts is defined
  tags: [ 'never', 'reformat_osts', 'format']
