---
osts:
  - name: nvme1n1
    index: 21
  - name: nvme2n1
    index: 22
  - name: nvme3n1
    index: 23
  - name: nvme4n1
    index: 24
  - name: nvme5n1
    index: 25
#  - name: nvme6n1
#    index: 6
#  - name: nvme7n1
#    index: 7
#  - name: nvme8n1
#    index: 8
#  - name: nvme9n1
#    index: 9
#  - name: nvme10n1
#    index: 10
#  - name: nvme11n1
#    index: 11

