---

- name: update ko2ib
  hosts: cpu
  gather_facts: no
  tasks:
    - name: update ko2ibopa
      lineinfile:
        path: /etc/modprobe.d/ko2iblnd.conf
        regexp: '^options ko2iblnd-opa'
        line: 'options ko2iblnd-opa peer_credits=128 peer_credits_hiw=64 credits=1024 ntx=2048 map_on_demand=32 fmr_pool_size=2048 fmr_flush_trigger=512 fmr_cache=1 conns_per_peer=4'

- name: config sys
  hosts: cpu
  gather_facts: no
  tasks:
    - name: hfi1
      lineinfile:
        path: /etc/modprobe.d/hfi1.conf
        regexp: '^options'
        line: 'options hfi1 krcvqs=8 pcie_caps=0x51 rcvhdrcnt=8192'


- name: setup BeeGFS
  hosts: cpu
  gather_facts: no
  roles:
    - beegfs
