---
osts:
  - name: nvme1n1
    index: 76
  - name: nvme2n1
    index: 77
  - name: nvme3n1
    index: 78
  - name: nvme4n1
    index: 79
  - name: nvme5n1
    index: 80
#  - name: nvme6n1
#    index: 6
#  - name: nvme7n1
#    index: 7
#  - name: nvme8n1
#    index: 8
#  - name: nvme9n1
#    index: 9
#  - name: nvme10n1
#    index: 10
#  - name: nvme11n1
#    index: 11

