---

- name: Build base RHEL
  hosts: dac
  gather_facts: no
  roles:
    - role: rhel

- name: Install BeeGFS
  hosts: dac
  gather_facts: no
  roles:
    - role: beegfs

- name: ib iface
  hosts: dac
  gather_facts: no
  tasks:
   - name: configure
     blockinfile:
       create: yes
       state: present
       path: /etc/sysconfig/network-scripts/ifcfg-{{ item.name }}
       block: |
          DEVICE={{ item.name }}
          TYPE='InfiniBand'
          BOOTPROTO=static
          IPADDR={{ item.addr }}
          BROADCAST=10.47.255.255
          NETWORK=10.47.0.0
          NETMASK=255.255.0.0
          ONBOOT=yes
          CONNECTED_MODE=yes
          MTU=65520
     with_items: "{{ ip }}"
     when:
       - ip is defined
       - item.name is match(target|default(".*"))

- name: config sys
  hosts: dac
  gather_facts: no
  tasks:
    - name: kernel params
      blockinfile:
        path: /etc/sysctl.conf
        block: |
          #kernel.msgmnb = 65536
          #kernel.msgmax = 65536
          #kernel.shmmax = 68719476736
          #kernel.shmall = 4294967296
          #vm.dirty_background_ratio = 5
          #vm.dirty_ratio = 20
          #vm.min_free_kbytes = 262144
          net.ipv4.conf.all.rp_filter=0
          net.ipv4.conf.ib0.arp_ignore=1
          net.ipv4.conf.ib0.arp_filter=0
          net.ipv4.conf.ib0.arp_announce=2
          net.ipv4.conf.ib0.rp_filter=0
          net.ipv4.conf.ib1.arp_ignore=1
          net.ipv4.conf.ib1.arp_filter=0
          net.ipv4.conf.ib1.arp_announce=2
          net.ipv4.conf.ib1.rp_filter=0

- name: Fix lustre multirail ip networking
  hosts: dac
  gather_facts: no
  roles:
    - role: lustre-multirail


- name: Install hpc ldap
  hosts: dac
  gather_facts: no
  tasks:
    - name: copy over certs
      copy:
        src: "{{ playbook_dir }}/files/{{ item }}"
        dest: "/etc/openldap/certs/{{ item }}"
        mode: 0600
      with_items:
        - darwincacert.pem
        - ldapserver.crt
        - cert8.db
        - key3.db
        - secmod.db
    - name: update hosts
      lineinfile:
        dest: /etc/hosts
        line: "128.232.224.2 ldap.xcat.cluster ldap"
        state: present
    - name: install sssd
      yum:
        name: sssd
        state: present
    - name: add sssd conf
      blockinfile:
        mode: 0600
        create: yes
        state: present
        path: /etc/sssd/sssd.conf
        block: |
          [domain/LDAP]
          cache_credentials = true
          id_provider = ldap

          [domain/cam]
          auth_provider = ldap
          cache_credentials = True
          chpass_provider = ldap
          enumerate = true
          id_provider = ldap
          ldap_enumeration_refresh_timeout = 43200
          ldap_id_use_start_tls = False
          ldap_purge_cache_timeout = 0
          ldap_search_base = dc=hpc,dc=cam,dc=ac,dc=uk
          ldap_tls_cacertdir = /etc/openldap/certs
          ldap_uri = ldaps://ldap.xcat.cluster

          [sssd]
          config_file_version = 2
          debug_level = 5
          domains = cam
          reconnection_retries = 3
          sbus_timeout = 30
          services = nss, pam
    - name: update nsswitch
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^passwd'
        line: 'passwd: files sss'
    - name: update nsswitch
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^shadow'
        line: 'shadow: files sss'
    - name: update nsswitch
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^group'
        line: 'group: files sss'
    - name: start sssd
      systemd:
        name: sssd
        state: started
        enabled: True



#    - role: yum-update
#
#
#- name: Install default rpms
#  hosts: dac
#  gather_facts: no
#  tasks:
#    - name: install list
#      yum:
#        name: '{{ item }}'
#        state: present
#      with_items:
#        - nvme-cli
#        - fio
#        - kernel*
#        - kernel-tools
#    - name: intall intel ssd dct
#      yum:
#        name: /tmp/isdct-3.0.12.400-17.x86_64.rpm
#        state: present
