---
- hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker
    docker_users:
      - "centos"
    docker_compose_version: "1.22.0"

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker

- hosts: all
  become: true
  tasks:
    - yum:
        name: git,go
        state: present

- hosts: all
  tasks:
    - file:
        path: ~/go/github.com/JohnGarbutt/
        state: directory
    - git:
        repo: 'https://github.com/JohnGarbutt/data-acc.git'
        dest: ~/go/src/github.com/JohnGarbutt/data-acc

- hosts: slurm-master[0]
  tasks:
    - docker_service:
        project_src: ~/go/src/github.com/JohnGarbutt/data-acc/ansible/slurm-master
        pull: true
      register: output
    - debug:
        var: output
    - name: ensure slurm cluster registered in db
      shell: |
        sleep 10 && docker exec slurmctld bash -c "/usr/bin/sacctmgr --immediate add cluster name=linux" && docker restart slurmdbd slurmctld
      when: output.changed

- hosts: slurm-workers
  tasks:
    - docker_service:
        project_src: ~/go/src/github.com/JohnGarbutt/data-acc/ansible/slurm-worker
        pull: true
      register: output
    - debug:
        var: output

- hosts: dac-workers
  tasks:
    - docker_service:
        project_src: ~/go/src/github.com/JohnGarbutt/data-acc/ansible/dac-worker
        pull: true
      register: output
    - debug:
        var: output
