---
- hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker
    docker_users:
      - "centos"

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker

- hosts: all
  become: true
  tasks:
    - yum:
        name: git,go
        state: present

- hosts: all
  tasks:
    - file:
        path: ~/go/github.com/JohnGarbutt/
        state: directory
    - git:
        repo: 'https://github.com/JohnGarbutt/data-acc.git'
        dest: ~/go/src/github.com/JohnGarbutt/data-acc

- hosts: slurm-master[0]
  tasks:
    - docker_service:
        project_src: ~/go/src/github.com/JohnGarbutt/data-acc/ansible/slurm-master
      register: output
    - debug:
        var: output

- hosts: slurm-workers
  tasks:
    - docker_service:
        project_src: ~/go/src/github.com/JohnGarbutt/data-acc/ansible/slurm-worker
      register: output
    - debug:
        var: output

- hosts: dac-workers
  tasks:
    - docker_service:
        project_src: ~/go/src/github.com/JohnGarbutt/data-acc/ansible/dac-worker
      register: output
    - debug:
        var: output
