---
- hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker

- hosts: all
  become: true
  tasks:
    - yum:
        name: git
        state: present
    - git:
        repo: 'https://github.com/JohnGarbutt/data-acc.git'
        dest: ~/jmfg2/data-acc

- hosts: swarm-manager[0]
  tasks:
    - name: determine swarm status
      shell: >
        docker info | egrep '^Swarm: ' | cut -d ' ' -f2
      register: swarm_status
    - name: initialize swarm cluster
      shell: docker swarm init --advertise-addr=em1:2377
      when: "'active' not in swarm_status.stdout_lines"
    - name: retrieve swarm worker token
      shell: docker swarm join-token -q worker
      register: swarm_worker_token

- hosts: swarm-workers
  vars:
    token: "{{ hostvars[groups['swarm-manager'][0]]['swarm_worker_token']['stdout'] }}"
  tasks:
    - name: determine swarm status
      shell: >
        docker info | egrep '^Swarm: ' | cut -d ' ' -f2
      register: swarm_status
    - name: join worker to swarm
      shell: docker swarm join --advertise-addr=em1:2377 --token={{ token }} {{ groups['swarm-manager'][0] }}:2377
      when: "'active' not in swarm_status.stdout_lines"

- hosts: swarm-manager[0]
  become: true
  tasks:
    - docker_service:
        project_src: ~/jmfg2/data-acc/docker-slurm
      register: output
    - debug:
        var: output
