---
- name: Ensure MGS has been formatted
  command: /usr/sbin/mkfs.lustre --mgs /dev/{{ mgs }}
      failed_when: "command_result.rc != 0 and ('was previously formatted for lustre' not in command_result.stderr)"
      changed_when: "command_result.rc == 0"
  when:
    - mgs is defined
  tags: [ 'never', 'format_mgs']

- name: Reformat MGS
  command: /usr/sbin/mkfs.lustre --mgs --reformat /dev/{{ mgs }}
  when:
    - mgs is defined
  tags: [ 'never', 'reformat_mgs']

- name: Reformat MDT
  command: /usr/sbin/mkfs.lustre --mdt --reformat --fsname={{ group_names[0] }} --index={{ index }} --mgsnode={{ mgsnode }} /dev/{{ item }}
  loop: "{{ mdts }}"
  loop_control:
    index_var: index
  when:
    - mdts is defined
  tags: [ 'never', 'reformat_mdts']

- name: Reformat OSTs
  command: /usr/sbin/mkfs.lustre --ost --reformat --fsname={{ group_names[0] }} --index={{ item.value }} --mgsnode={{ mgsnode }} /dev/{{ item.key }}
  loop: "{{ osts|default({})|dict2items }}"
  when:
    - osts is defined
  tags: [ 'never', 'reformat_osts']
