---
- name: Format MDT/MGS
  command: /usr/sbin/mkfs.lustre --mgs --mdt --reformat --fsname={{ group_names[0] }} --index={{ index }} --mgsnode={{ mgsnode }} /dev/{{ item }}
  loop: "{{ mdts }}"
  loop_control:
    index_var: index
  when:
    - mdts is defined
  tags: [ 'never', 'format_mdtmgs']

- name: Format OSTs
  command: /usr/sbin/mkfs.lustre --ost --reformat --fsname={{ group_names[0] }} --index={{ item.value }} --mgsnode={{ mgsnode }} /dev/{{ item.key }}
  loop: "{{ osts|dict2items}}"
  when:
    - osts is defined
  tags: [ 'never', 'format_osts']
