---
- name: load lustre module
  command: modprobe -v lustre
  tags: [ 'never', 'start_lustre']

- name: mount MDT/MGS
  command: mount -t lustre /dev/{{ item }} /lustre/{{ group_names[0] }}/MGSDT/{{ item }}
  loop: "{{ mdts }}"
  when:
    - mdts is defined
  tags: [ 'never', 'start_mgsdt', 'start_lustre']

- name: mount OSTs
  command: mount -t lustre /dev/{{ item }} /lustre/{{ group_names[0] }}/OST{{ item }}
  with_items: "{{ osts }}"
  when:
    - osts is defined
  tags: [ 'never', 'start_osts', 'start_lustre']

- name: umount all lustre
  command: umount -a -t lustre
  when:
    - osts is defined
  tags: [ 'never', 'stop_alllustre']
