---
- name: load lustre module
  command: modprobe -v lustre
  tags: [ 'never', 'start_lustre']


- name: Start MGS
  block:
    - name: Create MGS mount dir
      file:
        path: /lustre/MGS
        state: directory
        recurse: yes

    - name: mount MGSs
      command: mount -t lustre /dev/{{ mgs }} /lustre/MGS
      register: command_result
      failed_when: "command_result.rc != 0 and ('is already mounted' not in command_result.stderr)"
      changed_when: "command_result.rc == 0"
  when:
    - mgs is defined
  tags: [ 'never', 'start_mgs']


- name: Start MDTs
  block:
    - name: Create MGSDT mount dir
      file:
        path: /lustre/{{ fsname }}/MDT/{{ item }}
        state: directory
        recurse: yes
      with_items: "{{ mdts }}"

    - name: mount MDTs
      command: mount -t lustre /dev/{{ item }} /lustre/{{ fsname }}/MDT/{{ item }}
      register: command_result
      failed_when: "command_result.rc != 0 and ('is already mounted' not in command_result.stderr)"
      changed_when: "command_result.rc == 0"
      loop: "{{ mdts }}"

  when:
    - mdts is defined
  tags: [ 'never', 'start_mdts']


- name: Start OST
  block:
    - name: Create OST mount dir
      file:
        path: /lustre/{{ fsname }}/OST/{{ item }}
        state: directory
        recurse: yes
      with_items: "{{ osts }}"

    - name: mount OSTs
      command: mount -t lustre /dev/{{ item }} /lustre/{{ fsname }}/OST/{{ item }}
      register: command_result
      failed_when: "command_result.rc != 0 and ('is already mounted' not in command_result.stderr)"
      changed_when: "command_result.rc == 0"
      with_items: "{{ osts }}"

  when:
    - osts is defined
  tags: [ 'never', 'start_osts']


- name: Mount FS
  block:
    - name: ensure mount dir exists
      file:
        path: "/mnt/lustre/{{ fsname }}"
        state: directory
        recurse: yes
    - name: mount lustre fs
      command: mount -t lustre {{ mgsnode }}:/{{ fsname }} /mnt/lustre/{{ fsname }}
      register: command_result
      failed_when: "command_result.rc != 0 and ('is already mounted' not in command_result.stderr)"
      changed_when: "command_result.rc == 0"
  tags: [ 'never', 'mount_fs']


- name: umount FS
  block:
    - name: umount lustre fs
      command: "umount -l /mnt/lustre/{{ fsname }}"
      register: command_result
      failed_when: "command_result.rc != 0 and ('not mounted' not in command_result.stderr) and ('mountpoint not found' not in command_result.stderr)"
      changed_when: "command_result.rc == 0"

    - name: ensure mount dir deleted
      file:
        path: "/mnt/lustre/{{ fsname }}"
        state: absent
  tags: [ 'never', 'umount_fs']


- name: Stop OST
  block:
    - name: umount OSTs
      command: umount /lustre/{{ fsname }}/OST/{{ item }}
      register: command_result
      failed_when: "command_result.rc != 0 and ('not mounted' not in command_result.stderr) and ('mountpoint not found' not in command_result.stderr)"
      changed_when: "command_result.rc == 0"
      with_items: "{{ osts }}"

    - name: Remove OST mount dir
      file:
        path: /lustre/{{ fsname }}/OST
        state: absent
  when:
    - osts is defined
  tags: [ 'never', 'stop_osts']


- name: Stop MDTs
  block:
    - name: umount MDTs
      command: umount /lustre/{{ fsname }}/MDT/{{ item }}
      register: command_result
      failed_when: "command_result.rc != 0 and ('not mounted' not in command_result.stderr) and ('mountpoint not found' not in command_result.stderr)"
      changed_when: "command_result.rc == 0"
      loop: "{{ mdts }}"

    - name: Remove MGSDT mount dir
      file:
        path: /lustre/{{ fsname }}/MDT
        state: absent
  when:
    - mdts is defined
  tags: [ 'never', 'stop_mdts']


- name: Stop MGS
  block:
    - name: umount MGS
      command: umount /lustre/MGS
      register: command_result
      failed_when: "command_result.rc != 0 and ('not mounted' not in command_result.stderr) and ('mountpoint not found' not in command_result.stderr)"
      changed_when: "command_result.rc == 0"

    - name: Remove MGSDT mount dir
      file:
        path: /lustre/MGS
        state: absent
  when:
    - mgs is defined
  tags: [ 'never', 'stop_mgs']


- name: umount all lustre
  command: umount -a -t lustre
  when:
    - osts is defined
  tags: [ 'never', 'stop_alllustre']
