---
- hosts: etcd-master[0]
  roles:
    - role: andrewrothstein.pki
      pki_dir: /home/centos/pki-dir
      pki_self_sign: True
      pki_ca:
        cname: ca.dac.hpc.cam.ac.uk
      pki_servers:
        - cname: dac-etcd.dac.hpc.cam.ac.uk
        - cname: dac1.dac.hpc.cam.ac.uk
        - cname: dac2.dac.hpc.cam.ac.uk
        - cname: dac3.dac.hpc.cam.ac.uk

- hosts: etcd-master[0]
  tasks:
    - copy:
        src: /home/centos/pki-dir
        dest: ~/pki-dir
        remote_src: yes

- hosts: all
  become: true
  tasks:
  - name: configure default gateway
    command: route add default gw 10.43.255.1 || true

- hosts: etcd
  roles:
    - role: andrewrothstein.etcd-cluster
