---
- hosts: etcd-master[0]
  roles:
    - role: andrewrothstein.pki
      pki_dir: /home/centos/pki-dir
      pki_self_sign: True
      pki_ca:
        cname: ca.dac.hpc.cam.ac.uk
      pki_servers:
        - cname: dac-etcd.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac-etcd.dac.hpc.cam.ac.uk
          altips:
            - '10.43.101.30'
        - cname: dac1.dac.hpc.cam.ac.uk
        - cname: dac2.dac.hpc.cam.ac.uk
        - cname: dac3.dac.hpc.cam.ac.uk

- hosts: etcd-master[0]
  tasks:
    - fetch:
        src: /home/centos/pki-dir/{{item}}
        dest: ~/pki-dir/
        flat: yes
      with_items:
        - ca.pem
        - ca-key.pem
        - dac-etcd.dac.hpc.cam.ac.uk.pem
        - dac-etcd.dac.hpc.cam.ac.uk-key.pem

- hosts: all
  become: true
  tasks:
  - name: configure default gateway
    command: route add default gw 10.43.255.1 || true

- hosts: etcd
  roles:
    - role: andrewrothstein.etcd-cluster
      etcd_secure: False

- hosts: dac-workers
  roles:
    - role: data-acc
