---
- hosts: etcd-master[0]
  roles:
    - role: andrewrothstein.pki
      pki_dir: /home/centos/pki-dir
      pki_self_sign: True
      pki_ca:
        cname: ca.dac.hpc.cam.ac.uk
      pki_servers:
        - cname: dac-etcd.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac-etcd.dac.hpc.cam.ac.uk
          altips:
            - '10.43.101.30'
        - cname: dac1.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac1.dac.hpc.cam.ac.uk
        - cname: dac2.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac2.dac.hpc.cam.ac.uk
        - cname: dac3.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac3.dac.hpc.cam.ac.uk

- hosts: etcd-master[0]
  tasks:
    - fetch:
        src: /home/centos/pki-dir/{{item}}
        dest: ~/pki-dir/
        flat: yes
      with_items:
        - ca.pem
        - ca-key.pem
        - dac-etcd.dac.hpc.cam.ac.uk.pem
        - dac-etcd.dac.hpc.cam.ac.uk-key.pem
        - dac1.dac.hpc.cam.ac.uk.pem
        - dac1.dac.hpc.cam.ac.uk-key.pem
        - dac2.dac.hpc.cam.ac.uk.pem
        - dac2.dac.hpc.cam.ac.uk-key.pem
        - dac3.dac.hpc.cam.ac.uk.pem
        - dac3.dac.hpc.cam.ac.uk-key.pem

- hosts: all
  become: true
  tasks:
  - name: configure default gateway
    command: route add default gw 10.43.255.1 || true
  - name: Create entries in /etc/hosts for all nodes
    lineinfile:
      path: /etc/hosts
      line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}"
      regexp: "^.* {{ item }}$"
      create: no
      state: present
    with_items:
      - "{{ ansible_play_hosts }}"

- hosts: etcd
  roles:
    - role: andrewrothstein.etcd-cluster

- hosts: dac-workers
  roles:
    - role: data-acc
