---
- hosts: all
  tasks:
  - name: configure default gateway
    net_static_route:
      prefix: 10.43.0.0
      mask: 255.255.0.0
      next_hop: 10.43.255.1

- hosts: etcd
  roles:
    - andrewrothstein.etcd-cluster
