---
- hosts: etcd-master[0]
  roles:
    - role: andrewrothstein.pki
      pki_dir: /home/centos/pki-dir
      pki_self_sign: True
      pki_ca:
        cname: ca.dac.hpc.cam.ac.uk
      pki_servers:
        - cname: dac-etcd.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac-etcd.dac.hpc.cam.ac.uk
          altips:
            - '10.43.101.30'
        - cname: dac1.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac1.dac.hpc.cam.ac.uk
        - cname: dac2.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac2.dac.hpc.cam.ac.uk
        - cname: dac3.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac3.dac.hpc.cam.ac.uk

- hosts: etcd-master[0]
  tasks:
    - fetch:
        src: /home/centos/pki-dir/{{item}}
        dest: ~/pki-dir/
        flat: yes
      with_items:
        - ca.pem
        - ca-key.pem
        - dac-etcd.dac.hpc.cam.ac.uk.pem
        - dac-etcd.dac.hpc.cam.ac.uk-key.pem
        - dac1.dac.hpc.cam.ac.uk.pem
        - dac1.dac.hpc.cam.ac.uk-key.pem
        - dac2.dac.hpc.cam.ac.uk.pem
        - dac2.dac.hpc.cam.ac.uk-key.pem
        - dac3.dac.hpc.cam.ac.uk.pem
        - dac3.dac.hpc.cam.ac.uk-key.pem

- hosts: all
  become: true
  tasks:
  - name: configure default gateway
    command: route add default gw 10.43.255.1 || true
  - name: Create entries in /etc/hosts for all nodes
    lineinfile:
      path: /etc/hosts
      line: "{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['ansible_hostname'] }} {{ item }}"
      regexp: "^.* {{ item }}$"
      create: no
      state: present
    with_items:
      - "{{ ansible_play_hosts }}"

- hosts: etcd
  roles:
    - role: andrewrothstein.etcd-cluster

- hosts: dac-workers
  become: true
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip

- hosts: dac-workers
  roles:
    - role: data-acc

- hosts: dac-workers[0]
  become: true
  become_user: dac
  tasks:
    - name: Create ssh key for dac user for fs-ansible
      shell: |
        ssh-keygen -f /var/lib/dac/.ssh/id_rsa -t rsa -N ''
        cat /var/lib/dac/.ssh/id_rsa.pub >> /var/lib/dac/.ssh/authorized_keys
      args:
         creates: /var/lib/dac/.ssh/id_rsa
    - name: Pull Keys
      synchronize:
        mode: pull
        src:  /var/lib/dac/.ssh/
        dest: ~/.dac.ssh/
        recursive: yes

- hosts: dac-workers
  become: true
  tasks:
    - name: Push Keys for dac user for fs-ansible
      synchronize:
        mode: push
        src: ~/.dac.ssh/
        dest:  /var/lib/dac/.ssh/
        recursive: yes
    - name: trust host keys
      shell: |
        ssh-keyscan {{ hostvars[item]['ansible_default_ipv4']['address'] }} >> /var/lib/dac/.ssh/known_hosts
        ssh-keyscan {{ hostvars[item]['ansible_hostname'] }} >> /var/lib/dac/.ssh/known_hosts
        ssh-keyscan {{ item }} >> /var/lib/dac/.ssh/known_hosts
        touch /var/lib/dac/.ssh/.known{{ hostvars[item]['ansible_default_ipv4']['address'] }}
      args:
         creates: "/var/lib/dac/.ssh/.known{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
      with_items: "{{ ansible_play_hosts }}"
    - name: Fix up permissions on .ssh
      file:
        path: /var/lib/dac/.ssh
        owner: dac
        group: dac
        recurse: yes
    - name: Ensure passwordless sudo for dac user
      lineinfile:
        path: /etc/sudoers.d/80-dac
        line: "dac ALL=(ALL) NOPASSWD:ALL"
        regexp: "^dac.*$"
        create: yes
        state: present
